services:
  - type: web
    name: calidad-project
    env: python
    buildCommand: ""
    startCommand: gunicorn calidad_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: calidad_project.settings
      - key: PYTHON_VERSION
        value: "3.11"
